### ISSUE TITLE
TODO improvements

### ISSUE THREAD

**Issue by pranathivemuri** [czbiohub/napari-mosquito-bb-annotations#8]
Mosquitoes
- [x] hide console to size the images
- [x] Every time there is a property change add the summarize annotations table function, Summarize annotation - magicgui.widgets.Table(dict_of_lists) and list on the dock 
- [x] Defaulting everything except path on pranathi-lumi
- [x] Fix double click

RBCs
- [ ] Create two branches from the master with these changes for the 2 projects and deploy them, And use the taskbar to get the path and Default everything except path
- [ ] fix double click on the app using pyinstaller insted of py2app
- [ ] add tracking while inferencing possibly - maybe select all shapes and apply to next frame using options here - https://napari.org/tutorials/fundamentals/shapes.html

**Comment by pranathivemuri** [comment]
Inference as usual
1. Then apply to track- find the unique id's-- for the unique id's try and find the most repeated label as the label. Save it to the CSV file. 
2. Use the bounding box coordinates for separate images as the ones, don't modify the bounding boxes.
3. Update summary will change as well - the bounding box count will change depending on a column that's added by tracking that says the cell's unique ID- if the unique ID is repeated n times, then the count for that ID, label ID divided by that n and go to the next ID find a label and decimate it - Update the table that way. 
4. Cell tracking should add an ID column to the bb_labels.csv file
5. If someone edits a bounding box label it should be applied across frames somehow - to do that find ID for a label that was modified and find the index for that selected bounding box and update properties/refresh text for all those id's or index
Introduce another class for beads, white blood cells, and/or let edit by labels stay so people can add it. To get the percentage counts right, add a column for not just counts but the percentage of healthy and others
6. Set the mode to the select when edit label is clicked automatically
```shapes_layer.mode = 'select'
# set the shapes layer mode back to pan/zoom
shapes_layer.mode = 'pan_zoom'
```
7. Use magicgui table widget event instead - https://github.com/napari/magicgui/pull/209

**Comment by pranathivemuri** [comment]
no inference and then tracking = 5
inference and then tracking = 1
